### ISSUE TITLE
links not working on translated server

### ISSUE THREAD

**Issue by louisforget** [MediaBrowser/Emby#3002]
Hi Luke,
on the latest beta version (3.2.36.1) links seems not to be working as supposed: https://imgur.com/a/FxMHi

I have my preferred display language set as French, so I tried to change it for English and links are okay.
The issue seems to be related to translation.

I can test few other things for you if you want, just let me know!

Thanks

**Comment by LukePulverenti** [comment]
Hi, yes I pushed the beta without waiting for translations. It is resolved for the next update, thanks.

**Comment by louisforget** [comment]
Oh okay, was my first thought but I translated "links" string in the French page of OneSkyApp 18 hours ago and the version was released 3 hours ago so I thought that it was probably not related after all.. good then.. I will let you know if I still get "LinksValue" in the next version. :)

Thanks again!
